### PR TITLE
Add shutter flags for VH and PIP

### PR DESCRIPTION
**Pull request by chris-pateman**
### Change description ###
Add the Shutter Flags for both VH and PIP

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ X ] No
```

### CODE REVIEW

**Review by timja — CHANGES_REQUESTED** [review]
you shouldn't need this outside of sbox and prod shuttering should only be enabled there

https://github.com/hmcts/sds-azure-platform/blob/dec43c08e478222a120254752be43a2c4d18eff0/azure-pipelines.yaml#L61-L66

**Comment by chris-pateman** [comment]
@timja they have been removed from all other environments

> you shouldn't need this outside of sbox and prod shuttering should only be enabled there
> 
> https://github.com/hmcts/sds-azure-platform/blob/dec43c08e478222a120254752be43a2c4d18eff0/azure-pipelines.yaml#L61-L66

**Review by mark-butler-solirius — APPROVED** [review]
looks good to me

**Pull request merged**
